insert into `test`.`my_entity`(`name`, `need`, `count`) values 
	('motherboard', '1', '3');
	('processor', '1', '4'),
	('RAM', '1', '3'),
	('SSD', '1', '5'),
	('HDD', '0', '2'),
	('mouse', '0', '13'),
	('keyboard', '1', '8'),
	('sound card', '0', '5'),
	('video card', '0', '3'),
	('network card', '0', '2'),
	('card reader', '0', '1'),
	('motherboard', '1', '5'),
	('processor', '1', '6'),
	('RAM', '1', '7'),
	('SSD', '1', '9'),
	('HDD', '0', '11'),
	('mouse', '0', '3'),
	('keyboard', '1', '12'),
	('sound card', '0', '10'),
	('video card', '0', '8'),
	('network card', '0', '6'),
	('card reader', '0', '4'),
	('motherboard', '1', '2'),
	('processor', '1', '1'),
	('RAM', '1', '2'),
	('SSD', '1', '3'),
	('HDD', '0', '4'),
	('mouse', '0', '5'),
	('keyboard', '1', '6'),
	('sound card', '0', '7'),
	('video card', '0', '8'),
	('network card', '0', '9'),
	('card reader', '0', '10')